# This is a basic workflow to validate AWS CloudFormation Templates.

name: CloudFormation Validation

on:
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./api/template.yaml

  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./api
          skip_check: CKV_AWS_158
          quiet: true
          framework: cloudformation
          output_format: sarif
          log_level: WARNING
          container_user: 1000